name: snake_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pygame
  - pip
  - pip:
    - torch==2.1.0+cpu
    - --extra-index-url https://download.pytorch.org/whl/cpu
